[project]
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mlhw1"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.2,<3"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
scikit-learn = ">=1.5.2,<2"
jupyterlab = ">=4.2.5,<5"

[target.win-64.dependencies]
python = ">=3.12.7,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.2,<3"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
scikit-learn = ">=1.5.2,<2"
jupyterlab = ">=4.2.5,<5"

[target.linux-64.dependencies]
python = ">=3.13.0,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.2,<3"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
scikit-learn = ">=1.5.2,<2"
jupyterlab = ">=4.2.5,<5"

[target.osx-64.dependencies]
python = ">=3.13.0,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.2,<3"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
scikit-learn = ">=1.5.2,<2"
jupyterlab = ">=4.2.5,<5"
